[Quill] Shaheer / FEQ-1732 / slack notification on PR creation
deriv-com/quill-icons-park pull request #91
Opened 2024-02-16 11:35 UTC by shaheer-deriv

**Changes**
- Every time a new version of 📦 quill-icons-park is released (technically, after the GitHub Check Suite run is completed), this new workflow will be triggered.
- In case the deployment was successful, ✅ a success message and link to quill-icons-park app will be send as a slack notification.
- In case the deployment was not successful, ❌ a disappointing message and link to actions tab of repository will be send as a slack notification.
![image](https://github.com/deriv-com/quill-icons-park/assets/122449658/42cb8095-db6a-45ca-8d94-e4821804ac8b)

2024-02-19 02:01 UTC, niloofar-deriv commented on .github/workflows/send_slack_notifications.yaml
> +    name: Send New PR Slack notification
```suggestion
    name: Send Release Slack notification
```

2024-02-19 02:01 UTC, niloofar-deriv commented on .github/workflows/send_slack_notifications.yaml
> +    steps:
Can we add a message for successful or failed released? as an example please check the quill-icons release workflow

2024-02-26 02:00 UTC, niloofar-deriv approved these changes

2024-02-26 03:13 UTC, jim-deriv approved these changes

2024-02-26 06:41 UTC, prince-deriv requested changes

2024-02-26 06:41 UTC, prince-deriv commented on .github/workflows/release.yaml
> +          if [ "$CHECK_SUITE_CONCLUSION" == "success" ]; then
```suggestion
          if [ "$CHECK_SUITE_CONCLUSION" === "success" ]; then
```

2024-02-26 06:59 UTC, merged